version: '3'
services:
  db:
    image: postgres:9.3
    command: "postgres -c 'max_connections=500'"
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build: .
    environment:
      RAILS_ENV: production
    env_file:
      - .env
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"